### ISSUE TITLE
Es6 module import does not work.

### ISSUE THREAD

**Issue by pocorall** [tusharf5/runtime-memcache#4]
Thank you for your hard work to create this project.

I just tried to import this project with es6 module syntax:
```javascript
import createStore from 'https://unpkg.com/runtime-memcache';
```
which results:
```
Uncaught SyntaxError: The requested module 'https://unpkg.com/runtime-memcache' does not provide an export named 'default'
```
It would be nice if we can import this project from `unpkg.com` link.

**Comment by tusharf5** [comment]
Sure, I can work on it this weekend.

**Comment by tusharf5** [comment]
Hey @pocorall Browser module import is still not supported but I've added support to load it as a script tag in the browser. Check [Readme.md](https://github.com/tusharf5/runtime-memcache/blob/master/README.md) for more information.

I'll try to add support for importing directly in the browser via modules at a later time.

Thank you.

**Comment by pocorall** [comment]
Thanks, @tusharf5 !

It is now usable for my project; I am still hope to have a full es6 module support with unpkg.com link though.
