### ISSUE TITLE
Evict cached item based on its size

### ISSUE THREAD

**Issue by pocorall** [tusharf5/runtime-memcache#6]
Size-based eviction [something similar with that of caffeine](https://github.com/ben-manes/caffeine/wiki/Eviction).

**Comment by tusharf5** [comment]
I'm very busy nowadays but I'll work on this during the next couple of weekends :) 

I would like to know what type of size based eviction policy would make sense in this case. 

1. Size of number of keys (which is already there)
2. Actual size of objects (in bytes) stored in the cache.

**Comment by pocorall** [comment]
As the javascript cannot measure exact size of the object in bytes, we may specify size of the item when we put it into the cache.
